---
title: "ランダムネットワークにおける部分ネットワークの出現頻度の理論推定"
output: html_notebook
---

理論に基づいて，ランダムネットワークにおける部分ネットワークの出現頻度の推定を近似式から推定します。

  + Itzkovitz S, Milo R, Kashtan N, Ziv G and Alon U (2003) Subgraphs in random networks. Phys. Rev. E 68, 026127. https://doi.org/10.1103/PhysRevE.68.026127

```{r}
# igraphパッケージの読み込み
library(igraph)
```

### ノード数とエッジ数の設定
```{r}
# ノード数
N <- 1000
# エッジの数は2000から10000まで200ずつ増加させていく。
L_seq <- seq(2000, 10000, by=200)
```

### ランダムネットワークにおける部分ネットワークのカウント
```{r}
nb_ffl_real <- c() # feedforward loop (FFL) の実際の数（観測値）が格納される
nb_ffl_theory <- c() # 近似式から推定されたFFLの数（予測値）が格納される
nb_fbl_real <- c()  # feedback loop (FBL) の実際の数（観測値）が格納される
nb_fbl_theory <- c() # 近似式から推定されたFBLの数（予測値）が格納される

for(L in L_seq){
  # Chung-Luモデルネットワークの作成
  g <- static.power.law.game(N, L, 2.1, 2.1)
  
  # 単方向エッジのみのネットワークを作成
  g_one_way <- delete_edges(g, E(g)[which_mutual(g)==T])
  # 双方向エッジのみのネットワークを作成
  g_mutual <- delete_edges(g, E(g)[which_mutual(g)==F])
  
  # 各ノードの双方向エッジの数を得る
  M <- degree(g_mutual, mode="out")
  # 各ノードの単方向の出力エッジの数を得る
  K <- degree(g_one_way, mode="out")
  # 各ノードの単方向の入力エッジの数を得る
  R <- degree(g_one_way, mode="in")
  
  # 3ノード部分ネットワークをカウントする
  motif_real <- motifs(g, 3)
  
  # FFLの観測値を得る
  nb_ffl_real <- c(nb_ffl_real, motif_real[[8]])
  # FBLの観測値を得る
  nb_fbl_real <- c(nb_fbl_real, motif_real[[12]])
  
  # FFLの予測値を得る
  nb_ffl_theory <- c(nb_ffl_theory, mean(K*(K-1)) * mean(K*R) * mean(R*(R-1)) / mean(K)**3)
  # FBLの予測値を得る
  nb_fbl_theory <- c(nb_fbl_theory, mean(K*R)**3 / mean(K)**3 / 3)
}
```

### 結果をプロットする
```{r}
layout(matrix(1:2, ncol=2))
# FFL
plot(nb_ffl_real, nb_ffl_theory)
abline(0,1) # 対角線の追加
# FBL
plot(nb_fbl_real, nb_fbl_theory)
abline(0,1) # 対角線の追加
```
近似式からの予測は観測とよく一致していることがわかる。

# やってみよう
  + 別のネットワークモデルで調べてみよう。
  + 別の部分ネットワークについて調べてみよう。
    + 近似式は論文を参考のこと
