---
title: "Topological Overlap Matrixに基づくコミュニティ抽出"
output: html_notebook
---

代謝ネットワークの一部（解糖系・糖新生とTCA回路）を例にして，コミュニティ検出を行います。

```{r}
# igraphパッケージの読み込み
library(igraph)
```

### ネットワークの読み込み
```{r}
# エッジリスト形式のネットワークデータを読み込む
d <- read.table("../data/eco_EM+TCA.txt")
# 無向ネットワークで読み込む
g <- graph.data.frame(d, directed=F)
# 多重エッジや自己ループを削除する。
g <- simplify(g, remove.multiple=T, remove.loops=T)
```

### Topological overlap score matrixの計算
```{r}
# 隣接行列（Aij）を得る
A_ij <- get.adjacency(g,sparse=F)
# Jijの計算
J_ij <- cocitation(g)
# min(ki,kj)の計算
deg <- degree(g)
deg_mtx <- matrix(0,nrow=vcount(g),ncol=vcount(g))
for(i in 1:vcount(g)){
	for(j in 1:vcount(g)){
		deg_mtx[i,j] <- min(deg[[i]],deg[[j]])
	}
}

# Topological overlap score matrixを得る
overlap_mtx <- (J_ij + A_ij) / (deg_mtx + 1 - A_ij)
diag(overlap_mtx) <- 1
```

### 階層的クラスタリングの実行
```{r}
# 距離行列(dissimilarity score matrix)に変換
dist <- as.dist(1 - overlap_mtx)
# 群平均法に基づいて階層的クラスタリング
res <- hclust(dist, method="average")
# デンドログラムをプロット
plot(res)
```

### メンバーシップの取得
```{r}
# heightに対する適当な閾値hでコミュニティを決める場合
# mem <- cutree(res, h=0.9)
# k個数のコミュニティになるように分割する場合（ここでは2個に設定）
mem <- cutree(res, k=2)
mem
```

### コミュニティ検出の結果を表示
```{r}
# コミュニティのメンバシップにしたがってノードを色付け
V(g)$color <- mem
# ネットワークを描画。
set.seed(5)
plot(g,vertex.size=10, vertex.label=V(g)$name)
```
### モジュラリティ最大化による最適分割の決定
```{r}
q_max <- -Inf
nc_opt <- 1
nc_vs_q <- c() 
for(nc in 1:vcount(g)){
  mem <- cutree(res, k=nc)
  q <- modularity(g, mem)
  nc_vs_q  <- rbind(nc_vs_q, c(nc, q))
  if(q_max < q){
    nc_opt <- nc
    q_max <- q
  }
}
# コミュニティ数ncとその場合のモジュラリティQをプロット
plot(nc_vs_q, xlab="# of communities (nc)", ylab="Modularity Q")
```
```{r}
# モジュラリティQが最大となる分割を得る。
mem <- cutree(res, k=nc_opt)
# コミュニティのメンバシップにしたがってノードを色付け
V(g)$color <- mem
# ネットワークを描画。
set.seed(5)
plot(g,vertex.size=10, vertex.label=V(g)$name)
```

# やってみよう
  + このNotebookを参考にして，生物ネットワークを解析してみよう（``data``に様々ある）。
  + Notebookを参考に自分のデータを解析してみよう。